#!/bin/sh

set -e

if ! getent group "moira" > /dev/null 2>&1 ; then
  groupadd -r "moira"
fi
if ! getent passwd "moira" > /dev/null 2>&1 ; then
  useradd -r -g moira -d /usr/share/moira -s /sbin/nologin \
    -c "Moira user" moira
fi

mkdir -p /var/log/moira/worker
chown -R moira:moira /var/log/moira/worker
chmod 755 /var/log/moira/worker

if [ -x /bin/systemctl ] ; then
  /bin/systemctl daemon-reload
  /bin/systemctl enable moira-api.service
  /bin/systemctl enable moira-checker.service
elif [ -x /sbin/chkconfig ] ; then
  /sbin/chkconfig --add moira-api
  /sbin/chkconfig --add moira-checker
fi

